alias gs='git status'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias gl='git log --oneline --decorate --graph -20'
alias gd='git diff'
alias gds='git diff --staged'
# Controller battery check
alias batt='upower -i "$(upower -e | grep -Ei 'controller' | head -n1)"'
alias codium='flatpak run com.vscodium.codium'
export SYSTEMD_EDITOR=vi
export EDITOR=vi
export VISUAL=vi
#imhex flatpak bs
imhex() {
    if [ "$#" -eq 0 ]; then
        flatpak run net.werwolv.ImHex >/dev/null 2>&1 &
    else
        flatpak run --file-forwarding net.werwolv.ImHex @@ "$(realpath "$1")" @@ >/dev/null 2>&1 &
    fi
    disown
}
